version: '3.4'
services:
  auditable-override-acs:
    image: alfresco-content-services-auditable-override:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - auditable-override-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - auditable-override-postgres
  auditable-override-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - auditable-override-db-volume:/var/lib/postgresql/data
  auditable-override-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: auditable-override-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: auditable-override-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - auditable-override-ass-volume:/opt/alfresco-search-services/contentstore
      - auditable-override-ass-volume:/opt/alfresco-search-services/data
volumes:
  auditable-override-acs-volume:
    external: true
  auditable-override-db-volume:
    external: true
  auditable-override-ass-volume:
    external: true
